### ISSUE TITLE
SQL error after update: SQLSTATE[HY000]: General error: 1 near "WITH": syntax error

### ISSUE THREAD

**Issue by annda** [cosmocode/dokuwiki-plugin-structpublish#10]
How to reproduce:

- sqlite < 3.8.3, for example on CentOS 7
- update structpublish to version 2023-07-20

Stack trace in error log:

```
/var/www/wiki/lib/plugins/sqlite/SQLiteDB.php(124) PDOException: SQLSTATE[HY000]: General error: 1 near "WITH": syntax error
  #0 /var/www/wiki/lib/plugins/sqlite/SQLiteDB.php(185): dokuwiki\plugin\sqlite\SQLiteDB->query()
  #1 /var/www/wiki/lib/plugins/structpublish/action/migration.php(173): dokuwiki\plugin\sqlite\SQLiteDB->queryAll()
  #2 /var/www/wiki/lib/plugins/structpublish/action/migration.php(65): action_plugin_structpublish_migration->migration3()
  #3 /var/www/wiki/inc/Extension/EventHandler.php(80): action_plugin_structpublish_migration->handleMigrations()
  #4 /var/www/wiki/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
  #5 /var/www/wiki/inc/ActionRouter.php(80): dokuwiki\Extension\Event->advise_before()
  #6 /var/www/wiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction()
  #7 /var/www/wiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
  #8 /var/www/wiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance()
  #9 /var/www/wiki/doku.php(126): act_dispatch()
  #10 {main}
```

**Comment by annda** [comment]
Solution: update sqlite to at least 3.8.3

The most recent database migration (dbversion = 3) uses a common table expression in its SQL query, which was introduced in 3.8.3 on 2014-02-03, see https://www.sqlite.org/changes.html

Note: this query is executed only once. The plugin will work properly without it if somehow the database can be migrated manually or on another, more modern system.
